name: chatting_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  cloud_firestore: ^4.9.3
  date_format: ^2.0.7
  double_back_to_close_app: ^2.1.0
  firebase_analytics: ^10.5.1
  firebase_app_check: ^0.2.1+4
  firebase_auth: ^4.10.1
  firebase_core: ^2.17.0
  firebase_messaging: ^14.6.9
  firebase_storage: ^11.2.8
  fluent_appbar: ^2.0.0
  flutter:
    sdk: flutter
  flutter_image_compress: ^2.0.4
  image_picker: ^1.0.4
  intl: ^0.18.1
  page_transition: ^2.1.0
  path_provider: ^2.1.1
  provider: ^6.1.1
  proviso: ^1.0.5
  riverpod_annotation: ^2.3.0
  sqflite: ^2.3.0
  sugar: ^3.1.0
  time: ^2.1.3
  timezone: ^0.9.2
  uuid: ^3.0.7
  zego_uikit_prebuilt_call: ^3.17.9
  zego_uikit_signaling_plugin: ^2.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  custom_lint: ^0.5.6
  riverpod_lint: ^2.3.3
  riverpod_generator: ^2.3.5

flutter:
  uses-material-design: true
  assets:
    - assets/images/chat.png
    - assets/images/user.png
    - assets/images/group.jpeg
    - assets/images/ic_launcher_splash.png
    - assets/images/ic_launcher.png
    - assets/images/background.jpg
